version: '3.8'

services:
  # CPU version for local development
  whisper-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8000:8000"
    environment:
      - FORCE_CPU=1
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: python -u /rp_handler.py

  # CUDA version for production (requires nvidia-docker)
  whisper-cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python -u /rp_handler.py